/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TryRouteImport } from './routes/try'
import { Route as WaitlistAdminRouteImport } from './routes/waitlist-admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppFullMocksRouteImport } from './routes/_app.full-mocks'
import { Route as AppListeningRouteImport } from './routes/_app.listening'
import { Route as AppMistakesRouteImport } from './routes/_app.mistakes'
import { Route as AppPlanRouteImport } from './routes/_app.plan'
import { Route as AppPracticeRouteImport } from './routes/_app.practice'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppReadingRouteImport } from './routes/_app.reading'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSpeakingRouteImport } from './routes/_app.speaking'
import { Route as AppWritingRouteImport } from './routes/_app.writing'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminAiProvidersRouteImport } from './routes/admin.ai-providers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminFullMocksRouteImport } from './routes/admin.full-mocks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminPreviewRouteImport } from './routes/admin_.preview'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogBecomeWriterRouteImport } from './routes/blog.become-writer'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as BlogSitemapDotxmlRouteImport } from './routes/blog.sitemap[.]xml'
import { Route as RegisterVerifyRouteImport } from './routes/register.verify'
import { Route as AppAttemptsAttemptIdRouteImport } from './routes/_app.attempts.$attemptId'
import { Route as AppFullMockSessionsSessionIdRouteImport } from './routes/_app.full-mock-sessions.$sessionId'
import { Route as AppFullMocksMockIdRouteImport } from './routes/_app.full-mocks.$mockId'
import { Route as AppListeningTestIdRouteImport } from './routes/_app.listening.$testId'
import { Route as AppReadingMaterialIdRouteImport } from './routes/_app.reading.$materialId'
import { Route as AppSpeakingMaterialIdRouteImport } from './routes/_app.speaking.$materialId'
import { Route as AppWritingMaterialIdRouteImport } from './routes/_app.writing.$materialId'
import { Route as AdminBlogPostsRouteImport } from './routes/admin.blog.posts'
import { Route as AdminFullMocksIndexRouteImport } from './routes/admin.full-mocks.index'
import { Route as AdminFullMocksMockIdRouteImport } from './routes/admin.full-mocks.$mockId'
import { Route as AdminFullMocksNewRouteImport } from './routes/admin.full-mocks.new'
import { Route as AdminListeningImportRouteImport } from './routes/admin.listening.import'
import { Route as AdminListeningTestsRouteImport } from './routes/admin.listening.tests'
import { Route as AdminReadingImportRouteImport } from './routes/admin.reading.import'
import { Route as AdminReadingMaterialsRouteImport } from './routes/admin.reading.materials'
import { Route as AdminSpeakingImportRouteImport } from './routes/admin.speaking.import'
import { Route as AdminSpeakingMaterialsRouteImport } from './routes/admin.speaking.materials'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminWritersApplicationsRouteImport } from './routes/admin.writers.applications'
import { Route as AdminWritingImportRouteImport } from './routes/admin.writing.import'
import { Route as AdminWritingMaterialsRouteImport } from './routes/admin.writing.materials'
import { Route as ExamFullMockSessionsSessionIdRouteImport } from './routes/exam.full-mock-sessions.$sessionId'
import { Route as ExamListeningTestIdRouteImport } from './routes/exam.listening.$testId'
import { Route as ExamReadingMaterialIdRouteImport } from './routes/exam.reading.$materialId'
import { Route as ExamSpeakingMaterialIdRouteImport } from './routes/exam.speaking.$materialId'
import { Route as ExamWritingMaterialIdRouteImport } from './routes/exam.writing.$materialId'
import { Route as AppWriterPostsIndexRouteImport } from './routes/_app.writer.posts.index'
import { Route as AppWriterPostsPostIdRouteImport } from './routes/_app.writer.posts.$postId'
import { Route as AppWriterPostsNewRouteImport } from './routes/_app.writer.posts.new'
import { Route as AdminListeningTestsIndexRouteImport } from './routes/admin.listening.tests.index'
import { Route as AdminListeningTestsTestIdRouteImport } from './routes/admin.listening.tests.$testId'
import { Route as AdminListeningTestsNewRouteImport } from './routes/admin.listening.tests.new'
import { Route as AdminReadingMaterialsIndexRouteImport } from './routes/admin.reading.materials.index'
import { Route as AdminReadingMaterialsMaterialIdRouteImport } from './routes/admin.reading.materials.$materialId'
import { Route as AdminReadingMaterialsNewRouteImport } from './routes/admin.reading.materials.new'
import { Route as AdminSpeakingMaterialsIndexRouteImport } from './routes/admin.speaking.materials.index'
import { Route as AdminSpeakingMaterialsMaterialIdRouteImport } from './routes/admin.speaking.materials.$materialId'
import { Route as AdminSpeakingMaterialsNewRouteImport } from './routes/admin.speaking.materials.new'
import { Route as AdminWritingMaterialsIndexRouteImport } from './routes/admin.writing.materials.index'
import { Route as AdminWritingMaterialsMaterialIdRouteImport } from './routes/admin.writing.materials.$materialId'
import { Route as AdminWritingMaterialsNewRouteImport } from './routes/admin.writing.materials.new'
import { Route as AdminPreviewListeningTestIdRouteImport } from './routes/admin_.preview.listening.$testId'
import { Route as AdminPreviewReadingMaterialIdRouteImport } from './routes/admin_.preview.reading.$materialId'
import { Route as ExamFullMockSessionsSessionIdIndexRouteImport } from './routes/exam.full-mock-sessions.$sessionId.index'
import { Route as ExamFullMockSessionsSessionIdSectionsSectionPositionRouteImport } from './routes/exam.full-mock-sessions.$sessionId.sections.$sectionPosition'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistAdminRoute = WaitlistAdminRouteImport.update({
  id: '/waitlist-admin',
  path: '/waitlist-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFullMocksRoute = AppFullMocksRouteImport.update({
  id: '/full-mocks',
  path: '/full-mocks',
  getParentRoute: () => AppRoute,
} as any)
const AppListeningRoute = AppListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AppRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppReadingRoute = AppReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSpeakingRoute = AppSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => AppRoute,
} as any)
const AppWritingRoute = AppWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiProvidersRoute = AdminAiProvidersRouteImport.update({
  id: '/ai-providers',
  path: '/ai-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFullMocksRoute = AdminFullMocksRouteImport.update({
  id: '/full-mocks',
  path: '/full-mocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreviewRoute = AdminPreviewRouteImport.update({
  id: '/admin_/preview',
  path: '/admin/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogBecomeWriterRoute = BlogBecomeWriterRouteImport.update({
  id: '/blog/become-writer',
  path: '/blog/become-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSitemapDotxmlRoute = BlogSitemapDotxmlRouteImport.update({
  id: '/blog/sitemap.xml',
  path: '/blog/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterVerifyRoute = RegisterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => RegisterRoute,
} as any)
const AppAttemptsAttemptIdRoute = AppAttemptsAttemptIdRouteImport.update({
  id: '/attempts/$attemptId',
  path: '/attempts/$attemptId',
  getParentRoute: () => AppRoute,
} as any)
const AppFullMockSessionsSessionIdRoute =
  AppFullMockSessionsSessionIdRouteImport.update({
    id: '/full-mock-sessions/$sessionId',
    path: '/full-mock-sessions/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppFullMocksMockIdRoute = AppFullMocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => AppFullMocksRoute,
} as any)
const AppListeningTestIdRoute = AppListeningTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => AppListeningRoute,
} as any)
const AppReadingMaterialIdRoute = AppReadingMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => AppReadingRoute,
} as any)
const AppSpeakingMaterialIdRoute = AppSpeakingMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => AppSpeakingRoute,
} as any)
const AppWritingMaterialIdRoute = AppWritingMaterialIdRouteImport.update({
  id: '/$materialId',
  path: '/$materialId',
  getParentRoute: () => AppWritingRoute,
} as any)
const AdminBlogPostsRoute = AdminBlogPostsRouteImport.update({
  id: '/blog/posts',
  path: '/blog/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFullMocksIndexRoute = AdminFullMocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminFullMocksMockIdRoute = AdminFullMocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminFullMocksNewRoute = AdminFullMocksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminListeningImportRoute = AdminListeningImportRouteImport.update({
  id: '/listening/import',
  path: '/listening/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListeningTestsRoute = AdminListeningTestsRouteImport.update({
  id: '/listening/tests',
  path: '/listening/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadingImportRoute = AdminReadingImportRouteImport.update({
  id: '/reading/import',
  path: '/reading/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadingMaterialsRoute = AdminReadingMaterialsRouteImport.update({
  id: '/reading/materials',
  path: '/reading/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakingImportRoute = AdminSpeakingImportRouteImport.update({
  id: '/speaking/import',
  path: '/speaking/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakingMaterialsRoute = AdminSpeakingMaterialsRouteImport.update({
  id: '/speaking/materials',
  path: '/speaking/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminWritersApplicationsRoute =
  AdminWritersApplicationsRouteImport.update({
    id: '/writers/applications',
    path: '/writers/applications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminWritingImportRoute = AdminWritingImportRouteImport.update({
  id: '/writing/import',
  path: '/writing/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWritingMaterialsRoute = AdminWritingMaterialsRouteImport.update({
  id: '/writing/materials',
  path: '/writing/materials',
  getParentRoute: () => AdminRoute,
} as any)
const ExamFullMockSessionsSessionIdRoute =
  ExamFullMockSessionsSessionIdRouteImport.update({
    id: '/full-mock-sessions/$sessionId',
    path: '/full-mock-sessions/$sessionId',
    getParentRoute: () => ExamRoute,
  } as any)
const ExamListeningTestIdRoute = ExamListeningTestIdRouteImport.update({
  id: '/listening/$testId',
  path: '/listening/$testId',
  getParentRoute: () => ExamRoute,
} as any)
const ExamReadingMaterialIdRoute = ExamReadingMaterialIdRouteImport.update({
  id: '/reading/$materialId',
  path: '/reading/$materialId',
  getParentRoute: () => ExamRoute,
} as any)
const ExamSpeakingMaterialIdRoute = ExamSpeakingMaterialIdRouteImport.update({
  id: '/speaking/$materialId',
  path: '/speaking/$materialId',
  getParentRoute: () => ExamRoute,
} as any)
const ExamWritingMaterialIdRoute = ExamWritingMaterialIdRouteImport.update({
  id: '/writing/$materialId',
  path: '/writing/$materialId',
  getParentRoute: () => ExamRoute,
} as any)
const AppWriterPostsIndexRoute = AppWriterPostsIndexRouteImport.update({
  id: '/writer/posts/',
  path: '/writer/posts/',
  getParentRoute: () => AppRoute,
} as any)
const AppWriterPostsPostIdRoute = AppWriterPostsPostIdRouteImport.update({
  id: '/writer/posts/$postId',
  path: '/writer/posts/$postId',
  getParentRoute: () => AppRoute,
} as any)
const AppWriterPostsNewRoute = AppWriterPostsNewRouteImport.update({
  id: '/writer/posts/new',
  path: '/writer/posts/new',
  getParentRoute: () => AppRoute,
} as any)
const AdminListeningTestsIndexRoute =
  AdminListeningTestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminListeningTestsRoute,
  } as any)
const AdminListeningTestsTestIdRoute =
  AdminListeningTestsTestIdRouteImport.update({
    id: '/$testId',
    path: '/$testId',
    getParentRoute: () => AdminListeningTestsRoute,
  } as any)
const AdminListeningTestsNewRoute = AdminListeningTestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminListeningTestsRoute,
} as any)
const AdminReadingMaterialsIndexRoute =
  AdminReadingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminReadingMaterialsMaterialIdRoute =
  AdminReadingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminReadingMaterialsNewRoute =
  AdminReadingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsIndexRoute =
  AdminSpeakingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsMaterialIdRoute =
  AdminSpeakingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsNewRoute =
  AdminSpeakingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminWritingMaterialsIndexRoute =
  AdminWritingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)
const AdminWritingMaterialsMaterialIdRoute =
  AdminWritingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)
const AdminWritingMaterialsNewRoute =
  AdminWritingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)
const AdminPreviewListeningTestIdRoute =
  AdminPreviewListeningTestIdRouteImport.update({
    id: '/listening/$testId',
    path: '/listening/$testId',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const AdminPreviewReadingMaterialIdRoute =
  AdminPreviewReadingMaterialIdRouteImport.update({
    id: '/reading/$materialId',
    path: '/reading/$materialId',
    getParentRoute: () => AdminPreviewRoute,
  } as any)
const ExamFullMockSessionsSessionIdIndexRoute =
  ExamFullMockSessionsSessionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExamFullMockSessionsSessionIdRoute,
  } as any)
const ExamFullMockSessionsSessionIdSectionsSectionPositionRoute =
  ExamFullMockSessionsSessionIdSectionsSectionPositionRouteImport.update({
    id: '/sections/$sectionPosition',
    path: '/sections/$sectionPosition',
    getParentRoute: () => ExamFullMockSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/full-mocks': typeof AppFullMocksRouteWithChildren
  '/listening': typeof AppListeningRouteWithChildren
  '/mistakes': typeof AppMistakesRoute
  '/plan': typeof AppPlanRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/reading': typeof AppReadingRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/speaking': typeof AppSpeakingRouteWithChildren
  '/writing': typeof AppWritingRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/full-mocks': typeof AdminFullMocksRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/preview': typeof AdminPreviewRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/become-writer': typeof BlogBecomeWriterRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/attempts/$attemptId': typeof AppAttemptsAttemptIdRoute
  '/full-mock-sessions/$sessionId': typeof AppFullMockSessionsSessionIdRoute
  '/full-mocks/$mockId': typeof AppFullMocksMockIdRoute
  '/listening/$testId': typeof AppListeningTestIdRoute
  '/reading/$materialId': typeof AppReadingMaterialIdRoute
  '/speaking/$materialId': typeof AppSpeakingMaterialIdRoute
  '/writing/$materialId': typeof AppWritingMaterialIdRoute
  '/admin/blog/posts': typeof AdminBlogPostsRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/listening/tests': typeof AdminListeningTestsRouteWithChildren
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsRouteWithChildren
  '/admin/speaking/import': typeof AdminSpeakingImportRoute
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsRouteWithChildren
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/writers/applications': typeof AdminWritersApplicationsRoute
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsRouteWithChildren
  '/exam/full-mock-sessions/$sessionId': typeof ExamFullMockSessionsSessionIdRouteWithChildren
  '/exam/listening/$testId': typeof ExamListeningTestIdRoute
  '/exam/reading/$materialId': typeof ExamReadingMaterialIdRoute
  '/exam/speaking/$materialId': typeof ExamSpeakingMaterialIdRoute
  '/exam/writing/$materialId': typeof ExamWritingMaterialIdRoute
  '/admin/full-mocks/': typeof AdminFullMocksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/writer/posts/$postId': typeof AppWriterPostsPostIdRoute
  '/writer/posts/new': typeof AppWriterPostsNewRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin/preview/listening/$testId': typeof AdminPreviewListeningTestIdRoute
  '/admin/preview/reading/$materialId': typeof AdminPreviewReadingMaterialIdRoute
  '/writer/posts/': typeof AppWriterPostsIndexRoute
  '/admin/listening/tests/': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials/': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials/': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials/': typeof AdminWritingMaterialsIndexRoute
  '/exam/full-mock-sessions/$sessionId/': typeof ExamFullMockSessionsSessionIdIndexRoute
  '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition': typeof ExamFullMockSessionsSessionIdSectionsSectionPositionRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/full-mocks': typeof AppFullMocksRouteWithChildren
  '/listening': typeof AppListeningRouteWithChildren
  '/mistakes': typeof AppMistakesRoute
  '/plan': typeof AppPlanRoute
  '/practice': typeof AppPracticeRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/reading': typeof AppReadingRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/speaking': typeof AppSpeakingRouteWithChildren
  '/writing': typeof AppWritingRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin/preview': typeof AdminPreviewRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/become-writer': typeof BlogBecomeWriterRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/attempts/$attemptId': typeof AppAttemptsAttemptIdRoute
  '/full-mock-sessions/$sessionId': typeof AppFullMockSessionsSessionIdRoute
  '/full-mocks/$mockId': typeof AppFullMocksMockIdRoute
  '/listening/$testId': typeof AppListeningTestIdRoute
  '/reading/$materialId': typeof AppReadingMaterialIdRoute
  '/speaking/$materialId': typeof AppSpeakingMaterialIdRoute
  '/writing/$materialId': typeof AppWritingMaterialIdRoute
  '/admin/blog/posts': typeof AdminBlogPostsRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/speaking/import': typeof AdminSpeakingImportRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/writers/applications': typeof AdminWritersApplicationsRoute
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/exam/listening/$testId': typeof ExamListeningTestIdRoute
  '/exam/reading/$materialId': typeof ExamReadingMaterialIdRoute
  '/exam/speaking/$materialId': typeof ExamSpeakingMaterialIdRoute
  '/exam/writing/$materialId': typeof ExamWritingMaterialIdRoute
  '/admin/full-mocks': typeof AdminFullMocksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/writer/posts/$postId': typeof AppWriterPostsPostIdRoute
  '/writer/posts/new': typeof AppWriterPostsNewRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin/preview/listening/$testId': typeof AdminPreviewListeningTestIdRoute
  '/admin/preview/reading/$materialId': typeof AdminPreviewReadingMaterialIdRoute
  '/writer/posts': typeof AppWriterPostsIndexRoute
  '/admin/listening/tests': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsIndexRoute
  '/exam/full-mock-sessions/$sessionId': typeof ExamFullMockSessionsSessionIdIndexRoute
  '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition': typeof ExamFullMockSessionsSessionIdSectionsSectionPositionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/exam': typeof ExamRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRouteWithChildren
  '/terms': typeof TermsRoute
  '/try': typeof TryRoute
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/_app/full-mocks': typeof AppFullMocksRouteWithChildren
  '/_app/listening': typeof AppListeningRouteWithChildren
  '/_app/mistakes': typeof AppMistakesRoute
  '/_app/plan': typeof AppPlanRoute
  '/_app/practice': typeof AppPracticeRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/reading': typeof AppReadingRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/speaking': typeof AppSpeakingRouteWithChildren
  '/_app/writing': typeof AppWritingRouteWithChildren
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/ai-providers': typeof AdminAiProvidersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/full-mocks': typeof AdminFullMocksRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/admin_/preview': typeof AdminPreviewRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/become-writer': typeof BlogBecomeWriterRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/blog/sitemap.xml': typeof BlogSitemapDotxmlRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/_app/attempts/$attemptId': typeof AppAttemptsAttemptIdRoute
  '/_app/full-mock-sessions/$sessionId': typeof AppFullMockSessionsSessionIdRoute
  '/_app/full-mocks/$mockId': typeof AppFullMocksMockIdRoute
  '/_app/listening/$testId': typeof AppListeningTestIdRoute
  '/_app/reading/$materialId': typeof AppReadingMaterialIdRoute
  '/_app/speaking/$materialId': typeof AppSpeakingMaterialIdRoute
  '/_app/writing/$materialId': typeof AppWritingMaterialIdRoute
  '/admin/blog/posts': typeof AdminBlogPostsRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/listening/tests': typeof AdminListeningTestsRouteWithChildren
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsRouteWithChildren
  '/admin/speaking/import': typeof AdminSpeakingImportRoute
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsRouteWithChildren
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/writers/applications': typeof AdminWritersApplicationsRoute
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsRouteWithChildren
  '/exam/full-mock-sessions/$sessionId': typeof ExamFullMockSessionsSessionIdRouteWithChildren
  '/exam/listening/$testId': typeof ExamListeningTestIdRoute
  '/exam/reading/$materialId': typeof ExamReadingMaterialIdRoute
  '/exam/speaking/$materialId': typeof ExamSpeakingMaterialIdRoute
  '/exam/writing/$materialId': typeof ExamWritingMaterialIdRoute
  '/admin/full-mocks/': typeof AdminFullMocksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_app/writer/posts/$postId': typeof AppWriterPostsPostIdRoute
  '/_app/writer/posts/new': typeof AppWriterPostsNewRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin_/preview/listening/$testId': typeof AdminPreviewListeningTestIdRoute
  '/admin_/preview/reading/$materialId': typeof AdminPreviewReadingMaterialIdRoute
  '/_app/writer/posts/': typeof AppWriterPostsIndexRoute
  '/admin/listening/tests/': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials/': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials/': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials/': typeof AdminWritingMaterialsIndexRoute
  '/exam/full-mock-sessions/$sessionId/': typeof ExamFullMockSessionsSessionIdIndexRoute
  '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition': typeof ExamFullMockSessionsSessionIdSectionsSectionPositionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/exam'
    | '/forbidden'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/try'
    | '/waitlist-admin'
    | '/full-mocks'
    | '/listening'
    | '/mistakes'
    | '/plan'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/reading'
    | '/settings'
    | '/speaking'
    | '/writing'
    | '/admin/admins'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/full-mocks'
    | '/admin/users'
    | '/admin/waitlist'
    | '/admin/preview'
    | '/blog/$slug'
    | '/blog/become-writer'
    | '/blog/rss.xml'
    | '/blog/sitemap.xml'
    | '/register/verify'
    | '/admin/'
    | '/blog/'
    | '/attempts/$attemptId'
    | '/full-mock-sessions/$sessionId'
    | '/full-mocks/$mockId'
    | '/listening/$testId'
    | '/reading/$materialId'
    | '/speaking/$materialId'
    | '/writing/$materialId'
    | '/admin/blog/posts'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/listening/tests'
    | '/admin/reading/import'
    | '/admin/reading/materials'
    | '/admin/speaking/import'
    | '/admin/speaking/materials'
    | '/admin/users/$userId'
    | '/admin/writers/applications'
    | '/admin/writing/import'
    | '/admin/writing/materials'
    | '/exam/full-mock-sessions/$sessionId'
    | '/exam/listening/$testId'
    | '/exam/reading/$materialId'
    | '/exam/speaking/$materialId'
    | '/exam/writing/$materialId'
    | '/admin/full-mocks/'
    | '/admin/users/'
    | '/writer/posts/$postId'
    | '/writer/posts/new'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin/preview/listening/$testId'
    | '/admin/preview/reading/$materialId'
    | '/writer/posts/'
    | '/admin/listening/tests/'
    | '/admin/reading/materials/'
    | '/admin/speaking/materials/'
    | '/admin/writing/materials/'
    | '/exam/full-mock-sessions/$sessionId/'
    | '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/exam'
    | '/forbidden'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/try'
    | '/waitlist-admin'
    | '/full-mocks'
    | '/listening'
    | '/mistakes'
    | '/plan'
    | '/practice'
    | '/profile'
    | '/progress'
    | '/reading'
    | '/settings'
    | '/speaking'
    | '/writing'
    | '/admin/admins'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/waitlist'
    | '/admin/preview'
    | '/blog/$slug'
    | '/blog/become-writer'
    | '/blog/rss.xml'
    | '/blog/sitemap.xml'
    | '/register/verify'
    | '/'
    | '/admin'
    | '/blog'
    | '/attempts/$attemptId'
    | '/full-mock-sessions/$sessionId'
    | '/full-mocks/$mockId'
    | '/listening/$testId'
    | '/reading/$materialId'
    | '/speaking/$materialId'
    | '/writing/$materialId'
    | '/admin/blog/posts'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/reading/import'
    | '/admin/speaking/import'
    | '/admin/users/$userId'
    | '/admin/writers/applications'
    | '/admin/writing/import'
    | '/exam/listening/$testId'
    | '/exam/reading/$materialId'
    | '/exam/speaking/$materialId'
    | '/exam/writing/$materialId'
    | '/admin/full-mocks'
    | '/admin/users'
    | '/writer/posts/$postId'
    | '/writer/posts/new'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin/preview/listening/$testId'
    | '/admin/preview/reading/$materialId'
    | '/writer/posts'
    | '/admin/listening/tests'
    | '/admin/reading/materials'
    | '/admin/speaking/materials'
    | '/admin/writing/materials'
    | '/exam/full-mock-sessions/$sessionId'
    | '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/dashboard'
    | '/exam'
    | '/forbidden'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/try'
    | '/waitlist-admin'
    | '/_app/full-mocks'
    | '/_app/listening'
    | '/_app/mistakes'
    | '/_app/plan'
    | '/_app/practice'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/reading'
    | '/_app/settings'
    | '/_app/speaking'
    | '/_app/writing'
    | '/admin/admins'
    | '/admin/ai-providers'
    | '/admin/analytics'
    | '/admin/full-mocks'
    | '/admin/users'
    | '/admin/waitlist'
    | '/admin_/preview'
    | '/blog/$slug'
    | '/blog/become-writer'
    | '/blog/rss.xml'
    | '/blog/sitemap.xml'
    | '/register/verify'
    | '/_app/'
    | '/admin/'
    | '/blog/'
    | '/_app/attempts/$attemptId'
    | '/_app/full-mock-sessions/$sessionId'
    | '/_app/full-mocks/$mockId'
    | '/_app/listening/$testId'
    | '/_app/reading/$materialId'
    | '/_app/speaking/$materialId'
    | '/_app/writing/$materialId'
    | '/admin/blog/posts'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/listening/tests'
    | '/admin/reading/import'
    | '/admin/reading/materials'
    | '/admin/speaking/import'
    | '/admin/speaking/materials'
    | '/admin/users/$userId'
    | '/admin/writers/applications'
    | '/admin/writing/import'
    | '/admin/writing/materials'
    | '/exam/full-mock-sessions/$sessionId'
    | '/exam/listening/$testId'
    | '/exam/reading/$materialId'
    | '/exam/speaking/$materialId'
    | '/exam/writing/$materialId'
    | '/admin/full-mocks/'
    | '/admin/users/'
    | '/_app/writer/posts/$postId'
    | '/_app/writer/posts/new'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin_/preview/listening/$testId'
    | '/admin_/preview/reading/$materialId'
    | '/_app/writer/posts/'
    | '/admin/listening/tests/'
    | '/admin/reading/materials/'
    | '/admin/speaking/materials/'
    | '/admin/writing/materials/'
    | '/exam/full-mock-sessions/$sessionId/'
    | '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ExamRoute: typeof ExamRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  TermsRoute: typeof TermsRoute
  TryRoute: typeof TryRoute
  WaitlistAdminRoute: typeof WaitlistAdminRoute
  AdminPreviewRoute: typeof AdminPreviewRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogBecomeWriterRoute: typeof BlogBecomeWriterRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  BlogSitemapDotxmlRoute: typeof BlogSitemapDotxmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist-admin': {
      id: '/waitlist-admin'
      path: '/waitlist-admin'
      fullPath: '/waitlist-admin'
      preLoaderRoute: typeof WaitlistAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/full-mocks': {
      id: '/_app/full-mocks'
      path: '/full-mocks'
      fullPath: '/full-mocks'
      preLoaderRoute: typeof AppFullMocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listening': {
      id: '/_app/listening'
      path: '/listening'
      fullPath: '/listening'
      preLoaderRoute: typeof AppListeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mistakes': {
      id: '/_app/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan': {
      id: '/_app/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reading': {
      id: '/_app/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof AppReadingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/speaking': {
      id: '/_app/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof AppSpeakingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writing': {
      id: '/_app/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof AppWritingRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-providers': {
      id: '/admin/ai-providers'
      path: '/ai-providers'
      fullPath: '/admin/ai-providers'
      preLoaderRoute: typeof AdminAiProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/full-mocks': {
      id: '/admin/full-mocks'
      path: '/full-mocks'
      fullPath: '/admin/full-mocks'
      preLoaderRoute: typeof AdminFullMocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/preview': {
      id: '/admin_/preview'
      path: '/admin/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AdminPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/become-writer': {
      id: '/blog/become-writer'
      path: '/blog/become-writer'
      fullPath: '/blog/become-writer'
      preLoaderRoute: typeof BlogBecomeWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sitemap.xml': {
      id: '/blog/sitemap.xml'
      path: '/blog/sitemap.xml'
      fullPath: '/blog/sitemap.xml'
      preLoaderRoute: typeof BlogSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/verify': {
      id: '/register/verify'
      path: '/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof RegisterVerifyRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/_app/attempts/$attemptId': {
      id: '/_app/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/attempts/$attemptId'
      preLoaderRoute: typeof AppAttemptsAttemptIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/full-mock-sessions/$sessionId': {
      id: '/_app/full-mock-sessions/$sessionId'
      path: '/full-mock-sessions/$sessionId'
      fullPath: '/full-mock-sessions/$sessionId'
      preLoaderRoute: typeof AppFullMockSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/full-mocks/$mockId': {
      id: '/_app/full-mocks/$mockId'
      path: '/$mockId'
      fullPath: '/full-mocks/$mockId'
      preLoaderRoute: typeof AppFullMocksMockIdRouteImport
      parentRoute: typeof AppFullMocksRoute
    }
    '/_app/listening/$testId': {
      id: '/_app/listening/$testId'
      path: '/$testId'
      fullPath: '/listening/$testId'
      preLoaderRoute: typeof AppListeningTestIdRouteImport
      parentRoute: typeof AppListeningRoute
    }
    '/_app/reading/$materialId': {
      id: '/_app/reading/$materialId'
      path: '/$materialId'
      fullPath: '/reading/$materialId'
      preLoaderRoute: typeof AppReadingMaterialIdRouteImport
      parentRoute: typeof AppReadingRoute
    }
    '/_app/speaking/$materialId': {
      id: '/_app/speaking/$materialId'
      path: '/$materialId'
      fullPath: '/speaking/$materialId'
      preLoaderRoute: typeof AppSpeakingMaterialIdRouteImport
      parentRoute: typeof AppSpeakingRoute
    }
    '/_app/writing/$materialId': {
      id: '/_app/writing/$materialId'
      path: '/$materialId'
      fullPath: '/writing/$materialId'
      preLoaderRoute: typeof AppWritingMaterialIdRouteImport
      parentRoute: typeof AppWritingRoute
    }
    '/admin/blog/posts': {
      id: '/admin/blog/posts'
      path: '/blog/posts'
      fullPath: '/admin/blog/posts'
      preLoaderRoute: typeof AdminBlogPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/full-mocks/': {
      id: '/admin/full-mocks/'
      path: '/'
      fullPath: '/admin/full-mocks/'
      preLoaderRoute: typeof AdminFullMocksIndexRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/full-mocks/$mockId': {
      id: '/admin/full-mocks/$mockId'
      path: '/$mockId'
      fullPath: '/admin/full-mocks/$mockId'
      preLoaderRoute: typeof AdminFullMocksMockIdRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/full-mocks/new': {
      id: '/admin/full-mocks/new'
      path: '/new'
      fullPath: '/admin/full-mocks/new'
      preLoaderRoute: typeof AdminFullMocksNewRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/listening/import': {
      id: '/admin/listening/import'
      path: '/listening/import'
      fullPath: '/admin/listening/import'
      preLoaderRoute: typeof AdminListeningImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listening/tests': {
      id: '/admin/listening/tests'
      path: '/listening/tests'
      fullPath: '/admin/listening/tests'
      preLoaderRoute: typeof AdminListeningTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reading/import': {
      id: '/admin/reading/import'
      path: '/reading/import'
      fullPath: '/admin/reading/import'
      preLoaderRoute: typeof AdminReadingImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reading/materials': {
      id: '/admin/reading/materials'
      path: '/reading/materials'
      fullPath: '/admin/reading/materials'
      preLoaderRoute: typeof AdminReadingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speaking/import': {
      id: '/admin/speaking/import'
      path: '/speaking/import'
      fullPath: '/admin/speaking/import'
      preLoaderRoute: typeof AdminSpeakingImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speaking/materials': {
      id: '/admin/speaking/materials'
      path: '/speaking/materials'
      fullPath: '/admin/speaking/materials'
      preLoaderRoute: typeof AdminSpeakingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/writers/applications': {
      id: '/admin/writers/applications'
      path: '/writers/applications'
      fullPath: '/admin/writers/applications'
      preLoaderRoute: typeof AdminWritersApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/writing/import': {
      id: '/admin/writing/import'
      path: '/writing/import'
      fullPath: '/admin/writing/import'
      preLoaderRoute: typeof AdminWritingImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/writing/materials': {
      id: '/admin/writing/materials'
      path: '/writing/materials'
      fullPath: '/admin/writing/materials'
      preLoaderRoute: typeof AdminWritingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/exam/full-mock-sessions/$sessionId': {
      id: '/exam/full-mock-sessions/$sessionId'
      path: '/full-mock-sessions/$sessionId'
      fullPath: '/exam/full-mock-sessions/$sessionId'
      preLoaderRoute: typeof ExamFullMockSessionsSessionIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/listening/$testId': {
      id: '/exam/listening/$testId'
      path: '/listening/$testId'
      fullPath: '/exam/listening/$testId'
      preLoaderRoute: typeof ExamListeningTestIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/reading/$materialId': {
      id: '/exam/reading/$materialId'
      path: '/reading/$materialId'
      fullPath: '/exam/reading/$materialId'
      preLoaderRoute: typeof ExamReadingMaterialIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/speaking/$materialId': {
      id: '/exam/speaking/$materialId'
      path: '/speaking/$materialId'
      fullPath: '/exam/speaking/$materialId'
      preLoaderRoute: typeof ExamSpeakingMaterialIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/exam/writing/$materialId': {
      id: '/exam/writing/$materialId'
      path: '/writing/$materialId'
      fullPath: '/exam/writing/$materialId'
      preLoaderRoute: typeof ExamWritingMaterialIdRouteImport
      parentRoute: typeof ExamRoute
    }
    '/_app/writer/posts/': {
      id: '/_app/writer/posts/'
      path: '/writer/posts'
      fullPath: '/writer/posts/'
      preLoaderRoute: typeof AppWriterPostsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writer/posts/$postId': {
      id: '/_app/writer/posts/$postId'
      path: '/writer/posts/$postId'
      fullPath: '/writer/posts/$postId'
      preLoaderRoute: typeof AppWriterPostsPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/writer/posts/new': {
      id: '/_app/writer/posts/new'
      path: '/writer/posts/new'
      fullPath: '/writer/posts/new'
      preLoaderRoute: typeof AppWriterPostsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/listening/tests/': {
      id: '/admin/listening/tests/'
      path: '/'
      fullPath: '/admin/listening/tests/'
      preLoaderRoute: typeof AdminListeningTestsIndexRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/listening/tests/$testId': {
      id: '/admin/listening/tests/$testId'
      path: '/$testId'
      fullPath: '/admin/listening/tests/$testId'
      preLoaderRoute: typeof AdminListeningTestsTestIdRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/listening/tests/new': {
      id: '/admin/listening/tests/new'
      path: '/new'
      fullPath: '/admin/listening/tests/new'
      preLoaderRoute: typeof AdminListeningTestsNewRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/reading/materials/': {
      id: '/admin/reading/materials/'
      path: '/'
      fullPath: '/admin/reading/materials/'
      preLoaderRoute: typeof AdminReadingMaterialsIndexRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/reading/materials/$materialId': {
      id: '/admin/reading/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/reading/materials/$materialId'
      preLoaderRoute: typeof AdminReadingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/reading/materials/new': {
      id: '/admin/reading/materials/new'
      path: '/new'
      fullPath: '/admin/reading/materials/new'
      preLoaderRoute: typeof AdminReadingMaterialsNewRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/speaking/materials/': {
      id: '/admin/speaking/materials/'
      path: '/'
      fullPath: '/admin/speaking/materials/'
      preLoaderRoute: typeof AdminSpeakingMaterialsIndexRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/speaking/materials/$materialId': {
      id: '/admin/speaking/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/speaking/materials/$materialId'
      preLoaderRoute: typeof AdminSpeakingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/speaking/materials/new': {
      id: '/admin/speaking/materials/new'
      path: '/new'
      fullPath: '/admin/speaking/materials/new'
      preLoaderRoute: typeof AdminSpeakingMaterialsNewRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/writing/materials/': {
      id: '/admin/writing/materials/'
      path: '/'
      fullPath: '/admin/writing/materials/'
      preLoaderRoute: typeof AdminWritingMaterialsIndexRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
    '/admin/writing/materials/$materialId': {
      id: '/admin/writing/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/writing/materials/$materialId'
      preLoaderRoute: typeof AdminWritingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
    '/admin/writing/materials/new': {
      id: '/admin/writing/materials/new'
      path: '/new'
      fullPath: '/admin/writing/materials/new'
      preLoaderRoute: typeof AdminWritingMaterialsNewRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
    '/admin_/preview/listening/$testId': {
      id: '/admin_/preview/listening/$testId'
      path: '/listening/$testId'
      fullPath: '/admin/preview/listening/$testId'
      preLoaderRoute: typeof AdminPreviewListeningTestIdRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/admin_/preview/reading/$materialId': {
      id: '/admin_/preview/reading/$materialId'
      path: '/reading/$materialId'
      fullPath: '/admin/preview/reading/$materialId'
      preLoaderRoute: typeof AdminPreviewReadingMaterialIdRouteImport
      parentRoute: typeof AdminPreviewRoute
    }
    '/exam/full-mock-sessions/$sessionId/': {
      id: '/exam/full-mock-sessions/$sessionId/'
      path: '/'
      fullPath: '/exam/full-mock-sessions/$sessionId/'
      preLoaderRoute: typeof ExamFullMockSessionsSessionIdIndexRouteImport
      parentRoute: typeof ExamFullMockSessionsSessionIdRoute
    }
    '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition': {
      id: '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition'
      path: '/sections/$sectionPosition'
      fullPath: '/exam/full-mock-sessions/$sessionId/sections/$sectionPosition'
      preLoaderRoute: typeof ExamFullMockSessionsSessionIdSectionsSectionPositionRouteImport
      parentRoute: typeof ExamFullMockSessionsSessionIdRoute
    }
  }
}

interface AppFullMocksRouteChildren {
  AppFullMocksMockIdRoute: typeof AppFullMocksMockIdRoute
}

const AppFullMocksRouteChildren: AppFullMocksRouteChildren = {
  AppFullMocksMockIdRoute: AppFullMocksMockIdRoute,
}

const AppFullMocksRouteWithChildren = AppFullMocksRoute._addFileChildren(
  AppFullMocksRouteChildren,
)

interface AppListeningRouteChildren {
  AppListeningTestIdRoute: typeof AppListeningTestIdRoute
}

const AppListeningRouteChildren: AppListeningRouteChildren = {
  AppListeningTestIdRoute: AppListeningTestIdRoute,
}

const AppListeningRouteWithChildren = AppListeningRoute._addFileChildren(
  AppListeningRouteChildren,
)

interface AppReadingRouteChildren {
  AppReadingMaterialIdRoute: typeof AppReadingMaterialIdRoute
}

const AppReadingRouteChildren: AppReadingRouteChildren = {
  AppReadingMaterialIdRoute: AppReadingMaterialIdRoute,
}

const AppReadingRouteWithChildren = AppReadingRoute._addFileChildren(
  AppReadingRouteChildren,
)

interface AppSpeakingRouteChildren {
  AppSpeakingMaterialIdRoute: typeof AppSpeakingMaterialIdRoute
}

const AppSpeakingRouteChildren: AppSpeakingRouteChildren = {
  AppSpeakingMaterialIdRoute: AppSpeakingMaterialIdRoute,
}

const AppSpeakingRouteWithChildren = AppSpeakingRoute._addFileChildren(
  AppSpeakingRouteChildren,
)

interface AppWritingRouteChildren {
  AppWritingMaterialIdRoute: typeof AppWritingMaterialIdRoute
}

const AppWritingRouteChildren: AppWritingRouteChildren = {
  AppWritingMaterialIdRoute: AppWritingMaterialIdRoute,
}

const AppWritingRouteWithChildren = AppWritingRoute._addFileChildren(
  AppWritingRouteChildren,
)

interface AppRouteChildren {
  AppFullMocksRoute: typeof AppFullMocksRouteWithChildren
  AppListeningRoute: typeof AppListeningRouteWithChildren
  AppMistakesRoute: typeof AppMistakesRoute
  AppPlanRoute: typeof AppPlanRoute
  AppPracticeRoute: typeof AppPracticeRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppReadingRoute: typeof AppReadingRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSpeakingRoute: typeof AppSpeakingRouteWithChildren
  AppWritingRoute: typeof AppWritingRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppAttemptsAttemptIdRoute: typeof AppAttemptsAttemptIdRoute
  AppFullMockSessionsSessionIdRoute: typeof AppFullMockSessionsSessionIdRoute
  AppWriterPostsPostIdRoute: typeof AppWriterPostsPostIdRoute
  AppWriterPostsNewRoute: typeof AppWriterPostsNewRoute
  AppWriterPostsIndexRoute: typeof AppWriterPostsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFullMocksRoute: AppFullMocksRouteWithChildren,
  AppListeningRoute: AppListeningRouteWithChildren,
  AppMistakesRoute: AppMistakesRoute,
  AppPlanRoute: AppPlanRoute,
  AppPracticeRoute: AppPracticeRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppReadingRoute: AppReadingRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSpeakingRoute: AppSpeakingRouteWithChildren,
  AppWritingRoute: AppWritingRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppAttemptsAttemptIdRoute: AppAttemptsAttemptIdRoute,
  AppFullMockSessionsSessionIdRoute: AppFullMockSessionsSessionIdRoute,
  AppWriterPostsPostIdRoute: AppWriterPostsPostIdRoute,
  AppWriterPostsNewRoute: AppWriterPostsNewRoute,
  AppWriterPostsIndexRoute: AppWriterPostsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminFullMocksRouteChildren {
  AdminFullMocksMockIdRoute: typeof AdminFullMocksMockIdRoute
  AdminFullMocksNewRoute: typeof AdminFullMocksNewRoute
  AdminFullMocksIndexRoute: typeof AdminFullMocksIndexRoute
}

const AdminFullMocksRouteChildren: AdminFullMocksRouteChildren = {
  AdminFullMocksMockIdRoute: AdminFullMocksMockIdRoute,
  AdminFullMocksNewRoute: AdminFullMocksNewRoute,
  AdminFullMocksIndexRoute: AdminFullMocksIndexRoute,
}

const AdminFullMocksRouteWithChildren = AdminFullMocksRoute._addFileChildren(
  AdminFullMocksRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminListeningTestsRouteChildren {
  AdminListeningTestsTestIdRoute: typeof AdminListeningTestsTestIdRoute
  AdminListeningTestsNewRoute: typeof AdminListeningTestsNewRoute
  AdminListeningTestsIndexRoute: typeof AdminListeningTestsIndexRoute
}

const AdminListeningTestsRouteChildren: AdminListeningTestsRouteChildren = {
  AdminListeningTestsTestIdRoute: AdminListeningTestsTestIdRoute,
  AdminListeningTestsNewRoute: AdminListeningTestsNewRoute,
  AdminListeningTestsIndexRoute: AdminListeningTestsIndexRoute,
}

const AdminListeningTestsRouteWithChildren =
  AdminListeningTestsRoute._addFileChildren(AdminListeningTestsRouteChildren)

interface AdminReadingMaterialsRouteChildren {
  AdminReadingMaterialsMaterialIdRoute: typeof AdminReadingMaterialsMaterialIdRoute
  AdminReadingMaterialsNewRoute: typeof AdminReadingMaterialsNewRoute
  AdminReadingMaterialsIndexRoute: typeof AdminReadingMaterialsIndexRoute
}

const AdminReadingMaterialsRouteChildren: AdminReadingMaterialsRouteChildren = {
  AdminReadingMaterialsMaterialIdRoute: AdminReadingMaterialsMaterialIdRoute,
  AdminReadingMaterialsNewRoute: AdminReadingMaterialsNewRoute,
  AdminReadingMaterialsIndexRoute: AdminReadingMaterialsIndexRoute,
}

const AdminReadingMaterialsRouteWithChildren =
  AdminReadingMaterialsRoute._addFileChildren(
    AdminReadingMaterialsRouteChildren,
  )

interface AdminSpeakingMaterialsRouteChildren {
  AdminSpeakingMaterialsMaterialIdRoute: typeof AdminSpeakingMaterialsMaterialIdRoute
  AdminSpeakingMaterialsNewRoute: typeof AdminSpeakingMaterialsNewRoute
  AdminSpeakingMaterialsIndexRoute: typeof AdminSpeakingMaterialsIndexRoute
}

const AdminSpeakingMaterialsRouteChildren: AdminSpeakingMaterialsRouteChildren =
  {
    AdminSpeakingMaterialsMaterialIdRoute:
      AdminSpeakingMaterialsMaterialIdRoute,
    AdminSpeakingMaterialsNewRoute: AdminSpeakingMaterialsNewRoute,
    AdminSpeakingMaterialsIndexRoute: AdminSpeakingMaterialsIndexRoute,
  }

const AdminSpeakingMaterialsRouteWithChildren =
  AdminSpeakingMaterialsRoute._addFileChildren(
    AdminSpeakingMaterialsRouteChildren,
  )

interface AdminWritingMaterialsRouteChildren {
  AdminWritingMaterialsMaterialIdRoute: typeof AdminWritingMaterialsMaterialIdRoute
  AdminWritingMaterialsNewRoute: typeof AdminWritingMaterialsNewRoute
  AdminWritingMaterialsIndexRoute: typeof AdminWritingMaterialsIndexRoute
}

const AdminWritingMaterialsRouteChildren: AdminWritingMaterialsRouteChildren = {
  AdminWritingMaterialsMaterialIdRoute: AdminWritingMaterialsMaterialIdRoute,
  AdminWritingMaterialsNewRoute: AdminWritingMaterialsNewRoute,
  AdminWritingMaterialsIndexRoute: AdminWritingMaterialsIndexRoute,
}

const AdminWritingMaterialsRouteWithChildren =
  AdminWritingMaterialsRoute._addFileChildren(
    AdminWritingMaterialsRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAiProvidersRoute: typeof AdminAiProvidersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminFullMocksRoute: typeof AdminFullMocksRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogPostsRoute: typeof AdminBlogPostsRoute
  AdminListeningImportRoute: typeof AdminListeningImportRoute
  AdminListeningTestsRoute: typeof AdminListeningTestsRouteWithChildren
  AdminReadingImportRoute: typeof AdminReadingImportRoute
  AdminReadingMaterialsRoute: typeof AdminReadingMaterialsRouteWithChildren
  AdminSpeakingImportRoute: typeof AdminSpeakingImportRoute
  AdminSpeakingMaterialsRoute: typeof AdminSpeakingMaterialsRouteWithChildren
  AdminWritersApplicationsRoute: typeof AdminWritersApplicationsRoute
  AdminWritingImportRoute: typeof AdminWritingImportRoute
  AdminWritingMaterialsRoute: typeof AdminWritingMaterialsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAiProvidersRoute: AdminAiProvidersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminFullMocksRoute: AdminFullMocksRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogPostsRoute: AdminBlogPostsRoute,
  AdminListeningImportRoute: AdminListeningImportRoute,
  AdminListeningTestsRoute: AdminListeningTestsRouteWithChildren,
  AdminReadingImportRoute: AdminReadingImportRoute,
  AdminReadingMaterialsRoute: AdminReadingMaterialsRouteWithChildren,
  AdminSpeakingImportRoute: AdminSpeakingImportRoute,
  AdminSpeakingMaterialsRoute: AdminSpeakingMaterialsRouteWithChildren,
  AdminWritersApplicationsRoute: AdminWritersApplicationsRoute,
  AdminWritingImportRoute: AdminWritingImportRoute,
  AdminWritingMaterialsRoute: AdminWritingMaterialsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ExamFullMockSessionsSessionIdRouteChildren {
  ExamFullMockSessionsSessionIdIndexRoute: typeof ExamFullMockSessionsSessionIdIndexRoute
  ExamFullMockSessionsSessionIdSectionsSectionPositionRoute: typeof ExamFullMockSessionsSessionIdSectionsSectionPositionRoute
}

const ExamFullMockSessionsSessionIdRouteChildren: ExamFullMockSessionsSessionIdRouteChildren =
  {
    ExamFullMockSessionsSessionIdIndexRoute:
      ExamFullMockSessionsSessionIdIndexRoute,
    ExamFullMockSessionsSessionIdSectionsSectionPositionRoute:
      ExamFullMockSessionsSessionIdSectionsSectionPositionRoute,
  }

const ExamFullMockSessionsSessionIdRouteWithChildren =
  ExamFullMockSessionsSessionIdRoute._addFileChildren(
    ExamFullMockSessionsSessionIdRouteChildren,
  )

interface ExamRouteChildren {
  ExamFullMockSessionsSessionIdRoute: typeof ExamFullMockSessionsSessionIdRouteWithChildren
  ExamListeningTestIdRoute: typeof ExamListeningTestIdRoute
  ExamReadingMaterialIdRoute: typeof ExamReadingMaterialIdRoute
  ExamSpeakingMaterialIdRoute: typeof ExamSpeakingMaterialIdRoute
  ExamWritingMaterialIdRoute: typeof ExamWritingMaterialIdRoute
}

const ExamRouteChildren: ExamRouteChildren = {
  ExamFullMockSessionsSessionIdRoute:
    ExamFullMockSessionsSessionIdRouteWithChildren,
  ExamListeningTestIdRoute: ExamListeningTestIdRoute,
  ExamReadingMaterialIdRoute: ExamReadingMaterialIdRoute,
  ExamSpeakingMaterialIdRoute: ExamSpeakingMaterialIdRoute,
  ExamWritingMaterialIdRoute: ExamWritingMaterialIdRoute,
}

const ExamRouteWithChildren = ExamRoute._addFileChildren(ExamRouteChildren)

interface RegisterRouteChildren {
  RegisterVerifyRoute: typeof RegisterVerifyRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterVerifyRoute: RegisterVerifyRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface AdminPreviewRouteChildren {
  AdminPreviewListeningTestIdRoute: typeof AdminPreviewListeningTestIdRoute
  AdminPreviewReadingMaterialIdRoute: typeof AdminPreviewReadingMaterialIdRoute
}

const AdminPreviewRouteChildren: AdminPreviewRouteChildren = {
  AdminPreviewListeningTestIdRoute: AdminPreviewListeningTestIdRoute,
  AdminPreviewReadingMaterialIdRoute: AdminPreviewReadingMaterialIdRoute,
}

const AdminPreviewRouteWithChildren = AdminPreviewRoute._addFileChildren(
  AdminPreviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ExamRoute: ExamRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRouteWithChildren,
  TermsRoute: TermsRoute,
  TryRoute: TryRoute,
  WaitlistAdminRoute: WaitlistAdminRoute,
  AdminPreviewRoute: AdminPreviewRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogBecomeWriterRoute: BlogBecomeWriterRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  BlogSitemapDotxmlRoute: BlogSitemapDotxmlRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
