/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WaitlistAdminRouteImport } from './routes/waitlist-admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as AdminFullMocksRouteImport } from './routes/admin.full-mocks'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardFullMocksRouteImport } from './routes/dashboard.full-mocks'
import { Route as DashboardListeningRouteImport } from './routes/dashboard.listening'
import { Route as DashboardMistakesRouteImport } from './routes/dashboard.mistakes'
import { Route as DashboardPlanRouteImport } from './routes/dashboard.plan'
import { Route as DashboardPracticeRouteImport } from './routes/dashboard.practice'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProgressRouteImport } from './routes/dashboard.progress'
import { Route as DashboardReadingRouteImport } from './routes/dashboard.reading'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSpeakingRouteImport } from './routes/dashboard.speaking'
import { Route as DashboardWritingRouteImport } from './routes/dashboard.writing'
import { Route as RegisterVerifyRouteImport } from './routes/register.verify'
import { Route as AdminFullMocksIndexRouteImport } from './routes/admin.full-mocks.index'
import { Route as AdminFullMocksMockIdRouteImport } from './routes/admin.full-mocks.$mockId'
import { Route as AdminFullMocksNewRouteImport } from './routes/admin.full-mocks.new'
import { Route as AdminListeningImportRouteImport } from './routes/admin.listening.import'
import { Route as AdminListeningTestsRouteImport } from './routes/admin.listening.tests'
import { Route as AdminReadingImportRouteImport } from './routes/admin.reading.import'
import { Route as AdminReadingMaterialsRouteImport } from './routes/admin.reading.materials'
import { Route as AdminSpeakingMaterialsRouteImport } from './routes/admin.speaking.materials'
import { Route as AdminWritingImportRouteImport } from './routes/admin.writing.import'
import { Route as AdminWritingMaterialsRouteImport } from './routes/admin.writing.materials'
import { Route as DashboardAttemptsAttemptIdRouteImport } from './routes/dashboard.attempts.$attemptId'
import { Route as DashboardFullMockSessionsSessionIdRouteImport } from './routes/dashboard.full-mock-sessions.$sessionId'
import { Route as DashboardFullMocksMockIdRouteImport } from './routes/dashboard.full-mocks.$mockId'
import { Route as DashboardListeningTestIdRouteImport } from './routes/dashboard.listening.$testId'
import { Route as DashboardReadingMaterialIdRouteImport } from './routes/dashboard.reading.$materialId'
import { Route as DashboardSpeakingMaterialIdRouteImport } from './routes/dashboard.speaking.$materialId'
import { Route as DashboardWritingMaterialIdRouteImport } from './routes/dashboard.writing.$materialId'
import { Route as AdminListeningTestsIndexRouteImport } from './routes/admin.listening.tests.index'
import { Route as AdminListeningTestsTestIdRouteImport } from './routes/admin.listening.tests.$testId'
import { Route as AdminListeningTestsNewRouteImport } from './routes/admin.listening.tests.new'
import { Route as AdminReadingMaterialsIndexRouteImport } from './routes/admin.reading.materials.index'
import { Route as AdminReadingMaterialsMaterialIdRouteImport } from './routes/admin.reading.materials.$materialId'
import { Route as AdminReadingMaterialsNewRouteImport } from './routes/admin.reading.materials.new'
import { Route as AdminSpeakingMaterialsIndexRouteImport } from './routes/admin.speaking.materials.index'
import { Route as AdminSpeakingMaterialsMaterialIdRouteImport } from './routes/admin.speaking.materials.$materialId'
import { Route as AdminSpeakingMaterialsNewRouteImport } from './routes/admin.speaking.materials.new'
import { Route as AdminWritingMaterialsIndexRouteImport } from './routes/admin.writing.materials.index'
import { Route as AdminWritingMaterialsMaterialIdRouteImport } from './routes/admin.writing.materials.$materialId'
import { Route as AdminWritingMaterialsNewRouteImport } from './routes/admin.writing.materials.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistAdminRoute = WaitlistAdminRouteImport.update({
  id: '/waitlist-admin',
  path: '/waitlist-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFullMocksRoute = AdminFullMocksRouteImport.update({
  id: '/full-mocks',
  path: '/full-mocks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFullMocksRoute = DashboardFullMocksRouteImport.update({
  id: '/full-mocks',
  path: '/full-mocks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardListeningRoute = DashboardListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMistakesRoute = DashboardMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanRoute = DashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPracticeRoute = DashboardPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProgressRoute = DashboardProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReadingRoute = DashboardReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpeakingRoute = DashboardSpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWritingRoute = DashboardWritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => DashboardRoute,
} as any)
const RegisterVerifyRoute = RegisterVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => RegisterRoute,
} as any)
const AdminFullMocksIndexRoute = AdminFullMocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminFullMocksMockIdRoute = AdminFullMocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminFullMocksNewRoute = AdminFullMocksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminFullMocksRoute,
} as any)
const AdminListeningImportRoute = AdminListeningImportRouteImport.update({
  id: '/listening/import',
  path: '/listening/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListeningTestsRoute = AdminListeningTestsRouteImport.update({
  id: '/listening/tests',
  path: '/listening/tests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadingImportRoute = AdminReadingImportRouteImport.update({
  id: '/reading/import',
  path: '/reading/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReadingMaterialsRoute = AdminReadingMaterialsRouteImport.update({
  id: '/reading/materials',
  path: '/reading/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakingMaterialsRoute = AdminSpeakingMaterialsRouteImport.update({
  id: '/speaking/materials',
  path: '/speaking/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWritingImportRoute = AdminWritingImportRouteImport.update({
  id: '/writing/import',
  path: '/writing/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWritingMaterialsRoute = AdminWritingMaterialsRouteImport.update({
  id: '/writing/materials',
  path: '/writing/materials',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardAttemptsAttemptIdRoute =
  DashboardAttemptsAttemptIdRouteImport.update({
    id: '/attempts/$attemptId',
    path: '/attempts/$attemptId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFullMockSessionsSessionIdRoute =
  DashboardFullMockSessionsSessionIdRouteImport.update({
    id: '/full-mock-sessions/$sessionId',
    path: '/full-mock-sessions/$sessionId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFullMocksMockIdRoute =
  DashboardFullMocksMockIdRouteImport.update({
    id: '/$mockId',
    path: '/$mockId',
    getParentRoute: () => DashboardFullMocksRoute,
  } as any)
const DashboardListeningTestIdRoute =
  DashboardListeningTestIdRouteImport.update({
    id: '/$testId',
    path: '/$testId',
    getParentRoute: () => DashboardListeningRoute,
  } as any)
const DashboardReadingMaterialIdRoute =
  DashboardReadingMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => DashboardReadingRoute,
  } as any)
const DashboardSpeakingMaterialIdRoute =
  DashboardSpeakingMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => DashboardSpeakingRoute,
  } as any)
const DashboardWritingMaterialIdRoute =
  DashboardWritingMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => DashboardWritingRoute,
  } as any)
const AdminListeningTestsIndexRoute =
  AdminListeningTestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminListeningTestsRoute,
  } as any)
const AdminListeningTestsTestIdRoute =
  AdminListeningTestsTestIdRouteImport.update({
    id: '/$testId',
    path: '/$testId',
    getParentRoute: () => AdminListeningTestsRoute,
  } as any)
const AdminListeningTestsNewRoute = AdminListeningTestsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminListeningTestsRoute,
} as any)
const AdminReadingMaterialsIndexRoute =
  AdminReadingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminReadingMaterialsMaterialIdRoute =
  AdminReadingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminReadingMaterialsNewRoute =
  AdminReadingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminReadingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsIndexRoute =
  AdminSpeakingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsMaterialIdRoute =
  AdminSpeakingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminSpeakingMaterialsNewRoute =
  AdminSpeakingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminSpeakingMaterialsRoute,
  } as any)
const AdminWritingMaterialsIndexRoute =
  AdminWritingMaterialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)
const AdminWritingMaterialsMaterialIdRoute =
  AdminWritingMaterialsMaterialIdRouteImport.update({
    id: '/$materialId',
    path: '/$materialId',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)
const AdminWritingMaterialsNewRoute =
  AdminWritingMaterialsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminWritingMaterialsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/full-mocks': typeof AdminFullMocksRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/full-mocks': typeof DashboardFullMocksRouteWithChildren
  '/dashboard/listening': typeof DashboardListeningRouteWithChildren
  '/dashboard/mistakes': typeof DashboardMistakesRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRouteWithChildren
  '/dashboard/writing': typeof DashboardWritingRouteWithChildren
  '/register/verify': typeof RegisterVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/listening/tests': typeof AdminListeningTestsRouteWithChildren
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsRouteWithChildren
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsRouteWithChildren
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsRouteWithChildren
  '/dashboard/attempts/$attemptId': typeof DashboardAttemptsAttemptIdRoute
  '/dashboard/full-mock-sessions/$sessionId': typeof DashboardFullMockSessionsSessionIdRoute
  '/dashboard/full-mocks/$mockId': typeof DashboardFullMocksMockIdRoute
  '/dashboard/listening/$testId': typeof DashboardListeningTestIdRoute
  '/dashboard/reading/$materialId': typeof DashboardReadingMaterialIdRoute
  '/dashboard/speaking/$materialId': typeof DashboardSpeakingMaterialIdRoute
  '/dashboard/writing/$materialId': typeof DashboardWritingMaterialIdRoute
  '/admin/full-mocks/': typeof AdminFullMocksIndexRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin/listening/tests/': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials/': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials/': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials/': typeof AdminWritingMaterialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/full-mocks': typeof DashboardFullMocksRouteWithChildren
  '/dashboard/listening': typeof DashboardListeningRouteWithChildren
  '/dashboard/mistakes': typeof DashboardMistakesRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRouteWithChildren
  '/dashboard/writing': typeof DashboardWritingRouteWithChildren
  '/register/verify': typeof RegisterVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/dashboard/attempts/$attemptId': typeof DashboardAttemptsAttemptIdRoute
  '/dashboard/full-mock-sessions/$sessionId': typeof DashboardFullMockSessionsSessionIdRoute
  '/dashboard/full-mocks/$mockId': typeof DashboardFullMocksMockIdRoute
  '/dashboard/listening/$testId': typeof DashboardListeningTestIdRoute
  '/dashboard/reading/$materialId': typeof DashboardReadingMaterialIdRoute
  '/dashboard/speaking/$materialId': typeof DashboardSpeakingMaterialIdRoute
  '/dashboard/writing/$materialId': typeof DashboardWritingMaterialIdRoute
  '/admin/full-mocks': typeof AdminFullMocksIndexRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin/listening/tests': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRouteWithChildren
  '/waitlist-admin': typeof WaitlistAdminRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/full-mocks': typeof AdminFullMocksRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/dashboard/full-mocks': typeof DashboardFullMocksRouteWithChildren
  '/dashboard/listening': typeof DashboardListeningRouteWithChildren
  '/dashboard/mistakes': typeof DashboardMistakesRoute
  '/dashboard/plan': typeof DashboardPlanRoute
  '/dashboard/practice': typeof DashboardPracticeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/progress': typeof DashboardProgressRoute
  '/dashboard/reading': typeof DashboardReadingRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/speaking': typeof DashboardSpeakingRouteWithChildren
  '/dashboard/writing': typeof DashboardWritingRouteWithChildren
  '/register/verify': typeof RegisterVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/full-mocks/$mockId': typeof AdminFullMocksMockIdRoute
  '/admin/full-mocks/new': typeof AdminFullMocksNewRoute
  '/admin/listening/import': typeof AdminListeningImportRoute
  '/admin/listening/tests': typeof AdminListeningTestsRouteWithChildren
  '/admin/reading/import': typeof AdminReadingImportRoute
  '/admin/reading/materials': typeof AdminReadingMaterialsRouteWithChildren
  '/admin/speaking/materials': typeof AdminSpeakingMaterialsRouteWithChildren
  '/admin/writing/import': typeof AdminWritingImportRoute
  '/admin/writing/materials': typeof AdminWritingMaterialsRouteWithChildren
  '/dashboard/attempts/$attemptId': typeof DashboardAttemptsAttemptIdRoute
  '/dashboard/full-mock-sessions/$sessionId': typeof DashboardFullMockSessionsSessionIdRoute
  '/dashboard/full-mocks/$mockId': typeof DashboardFullMocksMockIdRoute
  '/dashboard/listening/$testId': typeof DashboardListeningTestIdRoute
  '/dashboard/reading/$materialId': typeof DashboardReadingMaterialIdRoute
  '/dashboard/speaking/$materialId': typeof DashboardSpeakingMaterialIdRoute
  '/dashboard/writing/$materialId': typeof DashboardWritingMaterialIdRoute
  '/admin/full-mocks/': typeof AdminFullMocksIndexRoute
  '/admin/listening/tests/$testId': typeof AdminListeningTestsTestIdRoute
  '/admin/listening/tests/new': typeof AdminListeningTestsNewRoute
  '/admin/reading/materials/$materialId': typeof AdminReadingMaterialsMaterialIdRoute
  '/admin/reading/materials/new': typeof AdminReadingMaterialsNewRoute
  '/admin/speaking/materials/$materialId': typeof AdminSpeakingMaterialsMaterialIdRoute
  '/admin/speaking/materials/new': typeof AdminSpeakingMaterialsNewRoute
  '/admin/writing/materials/$materialId': typeof AdminWritingMaterialsMaterialIdRoute
  '/admin/writing/materials/new': typeof AdminWritingMaterialsNewRoute
  '/admin/listening/tests/': typeof AdminListeningTestsIndexRoute
  '/admin/reading/materials/': typeof AdminReadingMaterialsIndexRoute
  '/admin/speaking/materials/': typeof AdminSpeakingMaterialsIndexRoute
  '/admin/writing/materials/': typeof AdminWritingMaterialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/waitlist-admin'
    | '/admin/admins'
    | '/admin/full-mocks'
    | '/admin/waitlist'
    | '/dashboard/full-mocks'
    | '/dashboard/listening'
    | '/dashboard/mistakes'
    | '/dashboard/plan'
    | '/dashboard/practice'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/writing'
    | '/register/verify'
    | '/admin/'
    | '/dashboard/'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/listening/tests'
    | '/admin/reading/import'
    | '/admin/reading/materials'
    | '/admin/speaking/materials'
    | '/admin/writing/import'
    | '/admin/writing/materials'
    | '/dashboard/attempts/$attemptId'
    | '/dashboard/full-mock-sessions/$sessionId'
    | '/dashboard/full-mocks/$mockId'
    | '/dashboard/listening/$testId'
    | '/dashboard/reading/$materialId'
    | '/dashboard/speaking/$materialId'
    | '/dashboard/writing/$materialId'
    | '/admin/full-mocks/'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin/listening/tests/'
    | '/admin/reading/materials/'
    | '/admin/speaking/materials/'
    | '/admin/writing/materials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/waitlist-admin'
    | '/admin/admins'
    | '/admin/waitlist'
    | '/dashboard/full-mocks'
    | '/dashboard/listening'
    | '/dashboard/mistakes'
    | '/dashboard/plan'
    | '/dashboard/practice'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/writing'
    | '/register/verify'
    | '/admin'
    | '/dashboard'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/reading/import'
    | '/admin/writing/import'
    | '/dashboard/attempts/$attemptId'
    | '/dashboard/full-mock-sessions/$sessionId'
    | '/dashboard/full-mocks/$mockId'
    | '/dashboard/listening/$testId'
    | '/dashboard/reading/$materialId'
    | '/dashboard/speaking/$materialId'
    | '/dashboard/writing/$materialId'
    | '/admin/full-mocks'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin/listening/tests'
    | '/admin/reading/materials'
    | '/admin/speaking/materials'
    | '/admin/writing/materials'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/register'
    | '/waitlist-admin'
    | '/admin/admins'
    | '/admin/full-mocks'
    | '/admin/waitlist'
    | '/dashboard/full-mocks'
    | '/dashboard/listening'
    | '/dashboard/mistakes'
    | '/dashboard/plan'
    | '/dashboard/practice'
    | '/dashboard/profile'
    | '/dashboard/progress'
    | '/dashboard/reading'
    | '/dashboard/settings'
    | '/dashboard/speaking'
    | '/dashboard/writing'
    | '/register/verify'
    | '/admin/'
    | '/dashboard/'
    | '/admin/full-mocks/$mockId'
    | '/admin/full-mocks/new'
    | '/admin/listening/import'
    | '/admin/listening/tests'
    | '/admin/reading/import'
    | '/admin/reading/materials'
    | '/admin/speaking/materials'
    | '/admin/writing/import'
    | '/admin/writing/materials'
    | '/dashboard/attempts/$attemptId'
    | '/dashboard/full-mock-sessions/$sessionId'
    | '/dashboard/full-mocks/$mockId'
    | '/dashboard/listening/$testId'
    | '/dashboard/reading/$materialId'
    | '/dashboard/speaking/$materialId'
    | '/dashboard/writing/$materialId'
    | '/admin/full-mocks/'
    | '/admin/listening/tests/$testId'
    | '/admin/listening/tests/new'
    | '/admin/reading/materials/$materialId'
    | '/admin/reading/materials/new'
    | '/admin/speaking/materials/$materialId'
    | '/admin/speaking/materials/new'
    | '/admin/writing/materials/$materialId'
    | '/admin/writing/materials/new'
    | '/admin/listening/tests/'
    | '/admin/reading/materials/'
    | '/admin/speaking/materials/'
    | '/admin/writing/materials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  WaitlistAdminRoute: typeof WaitlistAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist-admin': {
      id: '/waitlist-admin'
      path: '/waitlist-admin'
      fullPath: '/waitlist-admin'
      preLoaderRoute: typeof WaitlistAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/full-mocks': {
      id: '/admin/full-mocks'
      path: '/full-mocks'
      fullPath: '/admin/full-mocks'
      preLoaderRoute: typeof AdminFullMocksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/full-mocks': {
      id: '/dashboard/full-mocks'
      path: '/full-mocks'
      fullPath: '/dashboard/full-mocks'
      preLoaderRoute: typeof DashboardFullMocksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/listening': {
      id: '/dashboard/listening'
      path: '/listening'
      fullPath: '/dashboard/listening'
      preLoaderRoute: typeof DashboardListeningRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mistakes': {
      id: '/dashboard/mistakes'
      path: '/mistakes'
      fullPath: '/dashboard/mistakes'
      preLoaderRoute: typeof DashboardMistakesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plan': {
      id: '/dashboard/plan'
      path: '/plan'
      fullPath: '/dashboard/plan'
      preLoaderRoute: typeof DashboardPlanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/practice': {
      id: '/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof DashboardPracticeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/progress': {
      id: '/dashboard/progress'
      path: '/progress'
      fullPath: '/dashboard/progress'
      preLoaderRoute: typeof DashboardProgressRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reading': {
      id: '/dashboard/reading'
      path: '/reading'
      fullPath: '/dashboard/reading'
      preLoaderRoute: typeof DashboardReadingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/speaking': {
      id: '/dashboard/speaking'
      path: '/speaking'
      fullPath: '/dashboard/speaking'
      preLoaderRoute: typeof DashboardSpeakingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/writing': {
      id: '/dashboard/writing'
      path: '/writing'
      fullPath: '/dashboard/writing'
      preLoaderRoute: typeof DashboardWritingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/register/verify': {
      id: '/register/verify'
      path: '/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof RegisterVerifyRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/admin/full-mocks/': {
      id: '/admin/full-mocks/'
      path: '/'
      fullPath: '/admin/full-mocks/'
      preLoaderRoute: typeof AdminFullMocksIndexRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/full-mocks/$mockId': {
      id: '/admin/full-mocks/$mockId'
      path: '/$mockId'
      fullPath: '/admin/full-mocks/$mockId'
      preLoaderRoute: typeof AdminFullMocksMockIdRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/full-mocks/new': {
      id: '/admin/full-mocks/new'
      path: '/new'
      fullPath: '/admin/full-mocks/new'
      preLoaderRoute: typeof AdminFullMocksNewRouteImport
      parentRoute: typeof AdminFullMocksRoute
    }
    '/admin/listening/import': {
      id: '/admin/listening/import'
      path: '/listening/import'
      fullPath: '/admin/listening/import'
      preLoaderRoute: typeof AdminListeningImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listening/tests': {
      id: '/admin/listening/tests'
      path: '/listening/tests'
      fullPath: '/admin/listening/tests'
      preLoaderRoute: typeof AdminListeningTestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reading/import': {
      id: '/admin/reading/import'
      path: '/reading/import'
      fullPath: '/admin/reading/import'
      preLoaderRoute: typeof AdminReadingImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reading/materials': {
      id: '/admin/reading/materials'
      path: '/reading/materials'
      fullPath: '/admin/reading/materials'
      preLoaderRoute: typeof AdminReadingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speaking/materials': {
      id: '/admin/speaking/materials'
      path: '/speaking/materials'
      fullPath: '/admin/speaking/materials'
      preLoaderRoute: typeof AdminSpeakingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/writing/import': {
      id: '/admin/writing/import'
      path: '/writing/import'
      fullPath: '/admin/writing/import'
      preLoaderRoute: typeof AdminWritingImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/writing/materials': {
      id: '/admin/writing/materials'
      path: '/writing/materials'
      fullPath: '/admin/writing/materials'
      preLoaderRoute: typeof AdminWritingMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/attempts/$attemptId': {
      id: '/dashboard/attempts/$attemptId'
      path: '/attempts/$attemptId'
      fullPath: '/dashboard/attempts/$attemptId'
      preLoaderRoute: typeof DashboardAttemptsAttemptIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/full-mock-sessions/$sessionId': {
      id: '/dashboard/full-mock-sessions/$sessionId'
      path: '/full-mock-sessions/$sessionId'
      fullPath: '/dashboard/full-mock-sessions/$sessionId'
      preLoaderRoute: typeof DashboardFullMockSessionsSessionIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/full-mocks/$mockId': {
      id: '/dashboard/full-mocks/$mockId'
      path: '/$mockId'
      fullPath: '/dashboard/full-mocks/$mockId'
      preLoaderRoute: typeof DashboardFullMocksMockIdRouteImport
      parentRoute: typeof DashboardFullMocksRoute
    }
    '/dashboard/listening/$testId': {
      id: '/dashboard/listening/$testId'
      path: '/$testId'
      fullPath: '/dashboard/listening/$testId'
      preLoaderRoute: typeof DashboardListeningTestIdRouteImport
      parentRoute: typeof DashboardListeningRoute
    }
    '/dashboard/reading/$materialId': {
      id: '/dashboard/reading/$materialId'
      path: '/$materialId'
      fullPath: '/dashboard/reading/$materialId'
      preLoaderRoute: typeof DashboardReadingMaterialIdRouteImport
      parentRoute: typeof DashboardReadingRoute
    }
    '/dashboard/speaking/$materialId': {
      id: '/dashboard/speaking/$materialId'
      path: '/$materialId'
      fullPath: '/dashboard/speaking/$materialId'
      preLoaderRoute: typeof DashboardSpeakingMaterialIdRouteImport
      parentRoute: typeof DashboardSpeakingRoute
    }
    '/dashboard/writing/$materialId': {
      id: '/dashboard/writing/$materialId'
      path: '/$materialId'
      fullPath: '/dashboard/writing/$materialId'
      preLoaderRoute: typeof DashboardWritingMaterialIdRouteImport
      parentRoute: typeof DashboardWritingRoute
    }
    '/admin/listening/tests/': {
      id: '/admin/listening/tests/'
      path: '/'
      fullPath: '/admin/listening/tests/'
      preLoaderRoute: typeof AdminListeningTestsIndexRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/listening/tests/$testId': {
      id: '/admin/listening/tests/$testId'
      path: '/$testId'
      fullPath: '/admin/listening/tests/$testId'
      preLoaderRoute: typeof AdminListeningTestsTestIdRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/listening/tests/new': {
      id: '/admin/listening/tests/new'
      path: '/new'
      fullPath: '/admin/listening/tests/new'
      preLoaderRoute: typeof AdminListeningTestsNewRouteImport
      parentRoute: typeof AdminListeningTestsRoute
    }
    '/admin/reading/materials/': {
      id: '/admin/reading/materials/'
      path: '/'
      fullPath: '/admin/reading/materials/'
      preLoaderRoute: typeof AdminReadingMaterialsIndexRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/reading/materials/$materialId': {
      id: '/admin/reading/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/reading/materials/$materialId'
      preLoaderRoute: typeof AdminReadingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/reading/materials/new': {
      id: '/admin/reading/materials/new'
      path: '/new'
      fullPath: '/admin/reading/materials/new'
      preLoaderRoute: typeof AdminReadingMaterialsNewRouteImport
      parentRoute: typeof AdminReadingMaterialsRoute
    }
    '/admin/speaking/materials/': {
      id: '/admin/speaking/materials/'
      path: '/'
      fullPath: '/admin/speaking/materials/'
      preLoaderRoute: typeof AdminSpeakingMaterialsIndexRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/speaking/materials/$materialId': {
      id: '/admin/speaking/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/speaking/materials/$materialId'
      preLoaderRoute: typeof AdminSpeakingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/speaking/materials/new': {
      id: '/admin/speaking/materials/new'
      path: '/new'
      fullPath: '/admin/speaking/materials/new'
      preLoaderRoute: typeof AdminSpeakingMaterialsNewRouteImport
      parentRoute: typeof AdminSpeakingMaterialsRoute
    }
    '/admin/writing/materials/': {
      id: '/admin/writing/materials/'
      path: '/'
      fullPath: '/admin/writing/materials/'
      preLoaderRoute: typeof AdminWritingMaterialsIndexRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
    '/admin/writing/materials/$materialId': {
      id: '/admin/writing/materials/$materialId'
      path: '/$materialId'
      fullPath: '/admin/writing/materials/$materialId'
      preLoaderRoute: typeof AdminWritingMaterialsMaterialIdRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
    '/admin/writing/materials/new': {
      id: '/admin/writing/materials/new'
      path: '/new'
      fullPath: '/admin/writing/materials/new'
      preLoaderRoute: typeof AdminWritingMaterialsNewRouteImport
      parentRoute: typeof AdminWritingMaterialsRoute
    }
  }
}

interface AdminFullMocksRouteChildren {
  AdminFullMocksMockIdRoute: typeof AdminFullMocksMockIdRoute
  AdminFullMocksNewRoute: typeof AdminFullMocksNewRoute
  AdminFullMocksIndexRoute: typeof AdminFullMocksIndexRoute
}

const AdminFullMocksRouteChildren: AdminFullMocksRouteChildren = {
  AdminFullMocksMockIdRoute: AdminFullMocksMockIdRoute,
  AdminFullMocksNewRoute: AdminFullMocksNewRoute,
  AdminFullMocksIndexRoute: AdminFullMocksIndexRoute,
}

const AdminFullMocksRouteWithChildren = AdminFullMocksRoute._addFileChildren(
  AdminFullMocksRouteChildren,
)

interface AdminListeningTestsRouteChildren {
  AdminListeningTestsTestIdRoute: typeof AdminListeningTestsTestIdRoute
  AdminListeningTestsNewRoute: typeof AdminListeningTestsNewRoute
  AdminListeningTestsIndexRoute: typeof AdminListeningTestsIndexRoute
}

const AdminListeningTestsRouteChildren: AdminListeningTestsRouteChildren = {
  AdminListeningTestsTestIdRoute: AdminListeningTestsTestIdRoute,
  AdminListeningTestsNewRoute: AdminListeningTestsNewRoute,
  AdminListeningTestsIndexRoute: AdminListeningTestsIndexRoute,
}

const AdminListeningTestsRouteWithChildren =
  AdminListeningTestsRoute._addFileChildren(AdminListeningTestsRouteChildren)

interface AdminReadingMaterialsRouteChildren {
  AdminReadingMaterialsMaterialIdRoute: typeof AdminReadingMaterialsMaterialIdRoute
  AdminReadingMaterialsNewRoute: typeof AdminReadingMaterialsNewRoute
  AdminReadingMaterialsIndexRoute: typeof AdminReadingMaterialsIndexRoute
}

const AdminReadingMaterialsRouteChildren: AdminReadingMaterialsRouteChildren = {
  AdminReadingMaterialsMaterialIdRoute: AdminReadingMaterialsMaterialIdRoute,
  AdminReadingMaterialsNewRoute: AdminReadingMaterialsNewRoute,
  AdminReadingMaterialsIndexRoute: AdminReadingMaterialsIndexRoute,
}

const AdminReadingMaterialsRouteWithChildren =
  AdminReadingMaterialsRoute._addFileChildren(
    AdminReadingMaterialsRouteChildren,
  )

interface AdminSpeakingMaterialsRouteChildren {
  AdminSpeakingMaterialsMaterialIdRoute: typeof AdminSpeakingMaterialsMaterialIdRoute
  AdminSpeakingMaterialsNewRoute: typeof AdminSpeakingMaterialsNewRoute
  AdminSpeakingMaterialsIndexRoute: typeof AdminSpeakingMaterialsIndexRoute
}

const AdminSpeakingMaterialsRouteChildren: AdminSpeakingMaterialsRouteChildren =
  {
    AdminSpeakingMaterialsMaterialIdRoute:
      AdminSpeakingMaterialsMaterialIdRoute,
    AdminSpeakingMaterialsNewRoute: AdminSpeakingMaterialsNewRoute,
    AdminSpeakingMaterialsIndexRoute: AdminSpeakingMaterialsIndexRoute,
  }

const AdminSpeakingMaterialsRouteWithChildren =
  AdminSpeakingMaterialsRoute._addFileChildren(
    AdminSpeakingMaterialsRouteChildren,
  )

interface AdminWritingMaterialsRouteChildren {
  AdminWritingMaterialsMaterialIdRoute: typeof AdminWritingMaterialsMaterialIdRoute
  AdminWritingMaterialsNewRoute: typeof AdminWritingMaterialsNewRoute
  AdminWritingMaterialsIndexRoute: typeof AdminWritingMaterialsIndexRoute
}

const AdminWritingMaterialsRouteChildren: AdminWritingMaterialsRouteChildren = {
  AdminWritingMaterialsMaterialIdRoute: AdminWritingMaterialsMaterialIdRoute,
  AdminWritingMaterialsNewRoute: AdminWritingMaterialsNewRoute,
  AdminWritingMaterialsIndexRoute: AdminWritingMaterialsIndexRoute,
}

const AdminWritingMaterialsRouteWithChildren =
  AdminWritingMaterialsRoute._addFileChildren(
    AdminWritingMaterialsRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminFullMocksRoute: typeof AdminFullMocksRouteWithChildren
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListeningImportRoute: typeof AdminListeningImportRoute
  AdminListeningTestsRoute: typeof AdminListeningTestsRouteWithChildren
  AdminReadingImportRoute: typeof AdminReadingImportRoute
  AdminReadingMaterialsRoute: typeof AdminReadingMaterialsRouteWithChildren
  AdminSpeakingMaterialsRoute: typeof AdminSpeakingMaterialsRouteWithChildren
  AdminWritingImportRoute: typeof AdminWritingImportRoute
  AdminWritingMaterialsRoute: typeof AdminWritingMaterialsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminFullMocksRoute: AdminFullMocksRouteWithChildren,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListeningImportRoute: AdminListeningImportRoute,
  AdminListeningTestsRoute: AdminListeningTestsRouteWithChildren,
  AdminReadingImportRoute: AdminReadingImportRoute,
  AdminReadingMaterialsRoute: AdminReadingMaterialsRouteWithChildren,
  AdminSpeakingMaterialsRoute: AdminSpeakingMaterialsRouteWithChildren,
  AdminWritingImportRoute: AdminWritingImportRoute,
  AdminWritingMaterialsRoute: AdminWritingMaterialsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardFullMocksRouteChildren {
  DashboardFullMocksMockIdRoute: typeof DashboardFullMocksMockIdRoute
}

const DashboardFullMocksRouteChildren: DashboardFullMocksRouteChildren = {
  DashboardFullMocksMockIdRoute: DashboardFullMocksMockIdRoute,
}

const DashboardFullMocksRouteWithChildren =
  DashboardFullMocksRoute._addFileChildren(DashboardFullMocksRouteChildren)

interface DashboardListeningRouteChildren {
  DashboardListeningTestIdRoute: typeof DashboardListeningTestIdRoute
}

const DashboardListeningRouteChildren: DashboardListeningRouteChildren = {
  DashboardListeningTestIdRoute: DashboardListeningTestIdRoute,
}

const DashboardListeningRouteWithChildren =
  DashboardListeningRoute._addFileChildren(DashboardListeningRouteChildren)

interface DashboardReadingRouteChildren {
  DashboardReadingMaterialIdRoute: typeof DashboardReadingMaterialIdRoute
}

const DashboardReadingRouteChildren: DashboardReadingRouteChildren = {
  DashboardReadingMaterialIdRoute: DashboardReadingMaterialIdRoute,
}

const DashboardReadingRouteWithChildren =
  DashboardReadingRoute._addFileChildren(DashboardReadingRouteChildren)

interface DashboardSpeakingRouteChildren {
  DashboardSpeakingMaterialIdRoute: typeof DashboardSpeakingMaterialIdRoute
}

const DashboardSpeakingRouteChildren: DashboardSpeakingRouteChildren = {
  DashboardSpeakingMaterialIdRoute: DashboardSpeakingMaterialIdRoute,
}

const DashboardSpeakingRouteWithChildren =
  DashboardSpeakingRoute._addFileChildren(DashboardSpeakingRouteChildren)

interface DashboardWritingRouteChildren {
  DashboardWritingMaterialIdRoute: typeof DashboardWritingMaterialIdRoute
}

const DashboardWritingRouteChildren: DashboardWritingRouteChildren = {
  DashboardWritingMaterialIdRoute: DashboardWritingMaterialIdRoute,
}

const DashboardWritingRouteWithChildren =
  DashboardWritingRoute._addFileChildren(DashboardWritingRouteChildren)

interface DashboardRouteChildren {
  DashboardFullMocksRoute: typeof DashboardFullMocksRouteWithChildren
  DashboardListeningRoute: typeof DashboardListeningRouteWithChildren
  DashboardMistakesRoute: typeof DashboardMistakesRoute
  DashboardPlanRoute: typeof DashboardPlanRoute
  DashboardPracticeRoute: typeof DashboardPracticeRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProgressRoute: typeof DashboardProgressRoute
  DashboardReadingRoute: typeof DashboardReadingRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSpeakingRoute: typeof DashboardSpeakingRouteWithChildren
  DashboardWritingRoute: typeof DashboardWritingRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAttemptsAttemptIdRoute: typeof DashboardAttemptsAttemptIdRoute
  DashboardFullMockSessionsSessionIdRoute: typeof DashboardFullMockSessionsSessionIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFullMocksRoute: DashboardFullMocksRouteWithChildren,
  DashboardListeningRoute: DashboardListeningRouteWithChildren,
  DashboardMistakesRoute: DashboardMistakesRoute,
  DashboardPlanRoute: DashboardPlanRoute,
  DashboardPracticeRoute: DashboardPracticeRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProgressRoute: DashboardProgressRoute,
  DashboardReadingRoute: DashboardReadingRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSpeakingRoute: DashboardSpeakingRouteWithChildren,
  DashboardWritingRoute: DashboardWritingRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAttemptsAttemptIdRoute: DashboardAttemptsAttemptIdRoute,
  DashboardFullMockSessionsSessionIdRoute:
    DashboardFullMockSessionsSessionIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RegisterRouteChildren {
  RegisterVerifyRoute: typeof RegisterVerifyRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterVerifyRoute: RegisterVerifyRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRouteWithChildren,
  WaitlistAdminRoute: WaitlistAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
